from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd + '/include']
CPPPATH += [cwd + '/src']
CPPPATH += [cwd + '/src/common']

src = Glob('src/common/*.c')
SrcRemove(src, ['src/common/pf_snmp.c'])

group_common = DefineGroup('p-net/common', src, depend = [''], CPPPATH = CPPPATH)

CPPPATH = [cwd + '/src/device']
src = Glob('src/device/*.c')

group_device = DefineGroup('p-net/device', src, depend = [''], CPPPATH = CPPPATH)

group = group_common + group_device

Return('group')
