from building import *
import os

cwd     = GetCurrentDir()
src = Glob('*.c')
src += Glob('mib/*.c')

CPPPATH = [cwd]
CPPPATH += [cwd + '/mib']

group = DefineGroup('p-net/port', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
